BUS_NUMBER_URL_MAP = {
    8: (
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600980",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600983",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600987",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600989",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600990",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601028",
    ),
    26: (
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600956",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600957",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600961",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600975",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600982",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600991",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601008",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601011",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601012",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601014",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601015",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601018",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601019",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601025",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601027",
    ),
    66: (
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601202",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601209",
    ),
    58: (
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600730",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001600736",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601000",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601043",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601047",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601180",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601241",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601243",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601403",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601404",
    ),
    123: (
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601210",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601263",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601264",
    ),
    168: (
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601182",
        "https://navi.hamabus.city.yokohama.lg.jp/koutuu/pc/location/BusOperationResult?courseId=0001601211",
    ),
}
